# Generated by Django 3.0.5 on 2020-04-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_auto_20200424_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='song_file',
            field=models.FileField(upload_to='musics'),
        ),
    ]
